name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
        - [3.6, py36]
        - [3.7, py37]
        - [3.8, py38]
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version[0] }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version[0] }}
    - name: Install dependencies
      run: |
        pip install tox
    - run: tox -e ${{ matrix.python-version[1] }}
      env:
        LOG_LEVEL: DEBUG
        TEST_LOG_LEVEL: DEBUG